### ISSUE TITLE
Customize the index-server to be based around Winch.

### ISSUE THREAD

**Issue by brodycritchlow** [Winch-Team/IndexServer#3]
- [ ] Make sure version checking works
- [ ] Make sure every pypi / pip is replaced with winch

**Comment by tylercritchlow** [comment]
If we are using Vue for the rest of the site, will we have to use Tailwind or something to standardize the bar at the top and the colors? @brodycritchlow

**Comment by brodycritchlow** [comment]
Yep, I agree with that. And there is some other styling problems currently, such as some things being offset a little bit weird.

**Comment by tylercritchlow** [comment]
I made a branch. Is that going to be something we do soon, or should we put it off slightly?

**Comment by brodycritchlow** [comment]
Did we end up completing this task? @tylercritchlow

**Comment by tylercritchlow** [comment]
> Did we end up completing this task? @tylercritchlow 

Kind of, since we need to make it store versions separately, drop down menu for versions, etc.

You can make new issues more specific to that if you want, so that we can close this.

**Comment by brodycritchlow** [comment]
This is currently not a specific enough issue. We can recreate other issues with more specific details.
