### ISSUE TITLE
Setup package storage

### ISSUE THREAD

**Issue by brodycritchlow** [Winch-Team/IndexServer#9]
Currently, we have nothing being saved on our index-server.

We need this to be the (".zip") or similar file type, of the github repository.

This should also be related to versions. (Github Versions) #10

- [ ] Index server stores .zip file of the package's github repo

**Comment by tylercritchlow** [comment]
It may be worth it to use a separate file extension if we create a GUI package installer later to detect these local packages more easily.

`.wpkg` or `.winch`

- 

@brodycritchlow

**Comment by brodycritchlow** [comment]
Just as a note: we decided to go with `.wpkg` extension
